DRONE_ID = 3
DRONE_KEY = "rL/7mm7+p8neu4cyJVD80w=="
PARKVISION_SERVER = "127.0.0.1:29092"

# communication frequency
POSITION_SEND_INTERVAL = 0.5
STAGE_SEND_INTERVAL = 2
BAT_SEND_INTERVAL = 2
SAT_SEND_INTERVAL = 3

# flight specifics
PHOTO_ALTITUDE = 20
WAYPOINT_REACH_TOLERANCE_METERS = 0.25
ABOVE_GROUND_TOLERANCE_METERS = 0.25

# object detection
PHOTO_CENTER_DISTANCE_THRESHOLD_X = 0.25
PHOTO_CENTER_DISTANCE_THRESHOLD_Y = 0.25
OBJECT_SIZE_PROPORTION_THRESHOLD_X = 0.09
OBJECT_SIZE_PROPORTION_THRESHOLD_Y = 0.09